# Generated by Django 3.1.2 on 2020-11-09 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerInfo',
            fields=[
                ('server_id', models.AutoField(primary_key=True, serialize=False, verbose_name='压测机编号')),
                ('server_name', models.CharField(max_length=64, unique=True, verbose_name='压测机名称')),
                ('server_cloud', models.IntegerField(choices=[('huaweiCloud', '华为云'), ('tencentCloud', '腾讯云'), ('aliCloud', '阿里云')], max_length=64, unique=True, verbose_name='所属服务商')),
                ('server_status', models.IntegerField(choices=[(0, '可用'), (1, '忙碌'), (2, '下线')], max_length=64)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('task_name', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='任务名称')),
                ('busi_line', models.IntegerField(choices=[(0, '大数据部'), (1, '技术中台部'), (2, '经销商事业部')], null=True, verbose_name='业务线')),
                ('test_url', models.URLField(max_length=256)),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('s_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('exec_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceTest.serverinfo', verbose_name='所选压测机')),
            ],
        ),
    ]
