# Generated by Django 3.1.2 on 2020-11-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='server_cloud',
            field=models.CharField(choices=[('huaweiCloud', '华为云'), ('tencentCloud', '腾讯云'), ('aliCloud', '阿里云')], max_length=64, unique=True, verbose_name='所属服务商'),
        ),
    ]
