# Generated by Django 3.1.2 on 2020-11-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0002_auto_20201109_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='server_cloud',
            field=models.CharField(choices=[('huaweiCloud', '华为云'), ('tencentCloud', '腾讯云'), ('aliCloud', '阿里云')], max_length=64, verbose_name='所属服务商'),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='server_status',
            field=models.IntegerField(choices=[(0, '可用'), (1, '忙碌'), (2, '下线')]),
        ),
    ]
