# Generated by Django 3.1.2 on 2020-11-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0003_auto_20201110_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusiLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busi_id', models.IntegerField()),
                ('busi_name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='tasklist',
            name='stepTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='threadCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='urlPrama',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='busi_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceTest.busiline', verbose_name='业务线'),
        ),
    ]
