# Generated by Django 3.1.2 on 2020-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0004_auto_20201112_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='testTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
