# Generated by Django 3.1.2 on 2020-11-16 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0005_tasklist_testtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverinfo',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField()),
                ('task_name', models.CharField(blank=True, max_length=256, null=True)),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('s_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('exec_device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceTest.serverinfo', verbose_name='所选压测机')),
            ],
        ),
    ]
