# Generated by Django 3.1.2 on 2020-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0006_auto_20201116_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskresult',
            name='c_time',
        ),
        migrations.AddField(
            model_name='taskresult',
            name='TPS',
            field=models.FloatField(blank=True, null=True, verbose_name='tps/qps'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='avgResTime',
            field=models.FloatField(blank=True, null=True, verbose_name='平均响应时间'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='errorCounts',
            field=models.IntegerField(blank=True, null=True, verbose_name='错误总数'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='errorPct',
            field=models.FloatField(blank=True, null=True, verbose_name='错误率'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='madianResTime',
            field=models.FloatField(blank=True, null=True, verbose_name='中位响应时间'),
        ),
        migrations.AddField(
            model_name='taskresult',
            name='sampleCounts',
            field=models.IntegerField(blank=True, null=True, verbose_name='请求总数'),
        ),
    ]
