# Generated by Django 3.1.2 on 2020-11-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0007_auto_20201123_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskresult',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, '执行中'), (1, '已结束')], null=True, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='taskresult',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
