# Generated by Django 3.1.3 on 2020-11-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performanceTest', '0006_auto_20201116_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiInfo',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False, verbose_name='接口序号')),
                ('api_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='接口名称')),
                ('api_type', models.CharField(blank=True, choices=[(0, 'get'), (1, 'post')], max_length=64, null=True, verbose_name='请求类型')),
                ('api_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='请求地址')),
                ('api_c_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_busi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceTest.busiline', verbose_name='业务线')),
            ],
        ),
    ]
