# Generated by Django 3.1.3 on 2020-11-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20201118_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiinfo',
            name='api_apicontent',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='参数'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='api_apidesc',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='接口描述'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='api_contenttype',
            field=models.IntegerField(blank=True, choices=[(1, 'NONE'), (2, 'URL-ENCODE'), (3, 'JSON')], null=True, verbose_name='参数类型'),
        ),
        migrations.AlterField(
            model_name='apiinfo',
            name='api_type',
            field=models.IntegerField(blank=True, choices=[(0, 'get'), (1, 'post')], null=True, verbose_name='请求类型'),
        ),
    ]
