# Generated by Django 3.1.3 on 2020-11-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20201118_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='api_apicontent',
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='api_content',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='请求正文'),
        ),
        migrations.AddField(
            model_name='apiinfo',
            name='api_headers',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='请求头参数'),
        ),
    ]
