# Generated by Django 3.1.3 on 2020-11-25 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20201119_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='apiCase',
            fields=[
                ('apicase_id', models.AutoField(primary_key=True, serialize=False, verbose_name='case编号')),
                ('apicase_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='用例名称')),
                ('apicase_desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='用例描述')),
                ('apicase_params', models.CharField(blank=True, max_length=256, null=True, verbose_name='请求参数')),
                ('apicase_express', models.CharField(blank=True, max_length=256, null=True, verbose_name='表达式')),
                ('apicase_except', models.CharField(blank=True, max_length=256, null=True, verbose_name='期望值')),
                ('apicase_c_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('api_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apitest.apiinfo')),
            ],
        ),
    ]
