# Generated by Django 3.1.2 on 2020-12-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performanceTest', '0008_auto_20201124_1746'),
        ('apitest', '0006_auto_20201125_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicase',
            old_name='case_api_id',
            new_name='case_api',
        ),
        migrations.AddField(
            model_name='apicase',
            name='case_busi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='performanceTest.busiline'),
        ),
    ]
