# Generated by Django 3.1.2 on 2020-12-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_monitortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitortask',
            name='monitorTask_cron',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='执行cron'),
        ),
    ]
