# Generated by Django 3.1.2 on 2020-12-17 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0010_auto_20201210_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicase',
            name='case_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apitest.apiinfo'),
        ),
    ]
