# Generated by Django 3.1.2 on 2020-12-17 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_auto_20201217_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicase',
            name='case_api',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='apitest.apiinfo'),
        ),
    ]
